/*
  ----------- Function Prototypes -----------
*/
//handles keyboard operations
void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods);
//reconstructs objects
void reConstructObjects(Vertices *walls,
                        Vertices *menu,
                        Vertices *save1,
                        Vertices *save2,
                        Vertices *save3,
                        Vertices *save4,
                        Vertices *save5,
                        Vertices *savePlayGuest,
                        Vertices *menuPlay,
                        Vertices *menuProfile,
                        Vertices *menuSkins,
                        Vertices *menuSettings,
                        Vertices *menuRickRoll,
                        Vertices *settingsFullscreen,
                        Vertices *settingsResolution,
                        Vertices *settingsAudio,
                        Vertices *audio0,
                        Vertices *audio1,
                        Vertices *audio2,
                        Vertices *audio3,
                        Vertices *audio4,
                        Vertices *audio5,
                        Vertices *audio6,
                        Vertices *audio7,
                        Vertices *audio8,
                        Vertices *audio9,
                        Vertices *audio10,
                        Vertices *resolution1,
                        Vertices *resolution2,
                        Vertices *resolution3,
                        Vertices *resolution4,
                        Vertices *chooseAudioA,
                        Vertices *chooseAudioB,
                        Vertices *pauseGame,
                        Vertices *pauseMenu,
                        Vertices *next,
                        Vertices *hold,
                        Vertices *scoreVertices,
                        Vertices *levelVertices,
                        Vertices *sky,
                        Vertices *floor,
                        Vertices *zero,
                        Vertices *one,
                        Vertices *two,
                        Vertices *three,
                        Vertices *four,
                        Vertices *five,
                        Vertices *six,
                        Vertices *seven,
                        Vertices *eight,
                        Vertices *nine,
                        Vertices *zeroWhite,
                        Vertices *oneWhite,
                        Vertices *twoWhite,
                        Vertices *threeWhite,
                        Vertices *fourWhite,
                        Vertices *fiveWhite,
                        Vertices *sixWhite,
                        Vertices *sevenWhite,
                        Vertices *eightWhite,
                        Vertices *nineWhite,
                        Vertices *gameOverPlay,
                        Vertices *gameOverBack,
                        Vertices *highscoreVertices,
                        Vertices *skin0I,
                        Vertices *skin0J,
                        Vertices *skin0L,
                        Vertices *skin0T,
                        Vertices *skin0S,
                        Vertices *skin0Z,
                        Vertices *skin0O,
                        Vertices *skin1I,
                        Vertices *skin1J,
                        Vertices *skin1L,
                        Vertices *skin1T,
                        Vertices *skin1S,
                        Vertices *skin1Z,
                        Vertices *skin1O,
                        Vertices *skin2I,
                        Vertices *skin2J,
                        Vertices *skin2L,
                        Vertices *skin2T,
                        Vertices *skin2S,
                        Vertices *skin2Z,
                        Vertices *skin2O,
                        Vertices *skin11,
                        Vertices *skin21,
                        Vertices *skin22,
                        Vertices *skin31,
                        Vertices *skin32,
                        Vertices *skin33,
                        Vertices *unranked,
                        Vertices *bronze,
                        Vertices *silver,
                        Vertices *gold,
                        Vertices *platinum,
                        Vertices *diamond,
                        Vertices *master,
                        Vertices *tetris
                       );
//calls the necessary methods for every loop
void startLoop();
void endLoop();
//writes a 3d number
void CreateNumber(long long n, float x,float xInitial,float y, float z);
void CreateNumberWhite(long long n, float x,float xInitial,float y, float z);
//creates and instanciates a new player
void newPlayer();
void setInitialCameraPosition(float xPosition,
                              float yPosition,
                              float zPosition,
                              float positionSpeed,
                              float cameraSpeed,
                              float horizontalAngle,
                              float verticalAngle,
                              TRANSFORMATIONS *t);