/*
  ----------- Objects -----------
*/
OBJ_VECTORS //stages
            skyObject,
            floorObject,
            //tetrominoes
            cubeObject,
            nextObject,
            holdObject,
            //menus
            menuObject,
            //text
            scoreObject,
            lvlObject,
            highscoreObject,
            zeroObject,
            oneObject,
            twoObject,
            threeObject,
            fourObject,
            fiveObject,
            sixObject,
            sevenObject,
            eightObject,
            nineObject;
            
/*
  ----------- Buffers -----------
*/
BUFFERS //stages
        skyInfo,
        wallInfo,
        floorInfo,
        //menus
        menuInfo,
        //saves
        save1Info,
        save2Info,
        save3Info,
        save4Info,
        save5Info,
        savePlayGuestInfo,
        //main menu
        menuPlayInfo,
        menuRickRollInfo,
        //profile
        menuProfileInfo,
        unrankedInfo,
        bronzeInfo,
        silverInfo,
        goldInfo,
        platinumInfo,
        diamondInfo,
        masterInfo,
        tetrisInfo,
        //skins
        menuSkinsInfo,
        skin11Info,
        skin21Info,
        skin22Info,
        skin31Info,
        skin32Info,
        skin33Info,
        //settings
        menuSettingsInfo,
        settingsFullscreenInfo,
        settingsResolutionInfo,
        settingsAudioInfo,
        audio0Info,
        audio1Info,
        audio2Info,
        audio3Info,
        audio4Info,
        audio5Info,
        audio6Info,
        audio7Info,
        audio8Info,
        audio9Info,
        audio10Info,
        resolution1Info,
        resolution2Info,
        resolution3Info,
        resolution4Info,
        //choose audio
        chooseAudioAInfo,
        chooseAudioBInfo,
        //pause
        pauseGameInfo,
        pauseMenuInfo,
        //game over
        gameOverBackInfo,
        gameOverPlayInfo,
        //tetrominoes
        nextInfo,
        holdInfo,
        //text
        scoreInfo,
        lvlInfo,
        highscoreInfo,
        zeroInfo,
        oneInfo,
        twoInfo,
        threeInfo,
        fourInfo,
        fiveInfo,
        sixInfo,
        sevenInfo,
        eightInfo,
        nineInfo,
        zeroWhiteInfo,
        oneWhiteInfo,
        twoWhiteInfo,
        threeWhiteInfo,
        fourWhiteInfo,
        fiveWhiteInfo,
        sixWhiteInfo,
        sevenWhiteInfo,
        eightWhiteInfo,
        nineWhiteInfo,
        //skins
        //tetris
        skin0IInfo,
        skin0JInfo,
        skin0LInfo,
        skin0TInfo,
        skin0SInfo,
        skin0ZInfo,
        skin0OInfo,
        //doom
        skin1IInfo,
        skin1JInfo,
        skin1LInfo,
        skin1TInfo,
        skin1SInfo,
        skin1ZInfo,
        skin1OInfo,
        //minecraft
        skin2IInfo,
        skin2JInfo,
        skin2LInfo,
        skin2TInfo,
        skin2SInfo,
        skin2ZInfo,
        skin2OInfo;

/*
----------- Transformations -----------
*/
TRANSFORMATIONS t,
                t2,
                t3,
                t4,
                t5,
                t6,
                t7,
                t8,
                t9,
                t10;